### ISSUE TITLE
Missing cards in draft

### ISSUE THREAD

**Issue by jasoncowan25** [hansenwebco/marvel-snap-draft#29]
Missing cards such as Cosmo and Shangchi

**Comment by jasoncowan25** [comment]
Eventually Cosmo will show up but it is rare. Still havent seen Shangchi. Some cards show up every round like rocket raccoon. Double check odds in code?

**Comment by hansenwebco** [comment]
I reviewed the code again this morning and ran a few drafts and these cards do show up.  There's no logic that pulls cards more or less often so you're likely witnessing normal variance with a decent size set of cards.
